[workspace]
members = ["tuic", "tuic-quinn", "tuic-server", "tuic-client"]

[profile.release]
opt-level = 'z'
debug = 1
lto = true
incremental = false
codegen-units = 1
strip = "debuginfo"
panic = "abort"
