[package]
name = "tuic-server"
version = "1.0.1"
authors = ["EAimTY <ea.imty@gmail.com>"]
description = "Minimalistic TUIC server implementation as a reference"
categories = ["network-programming"]
keywords = ["network", "proxy", "quic", "tuic"]
edition = "2021"
rust-version = "1.65.0"
readme = "README.md"
license = "GPL-3.0-or-later"
repository = "https://github.com/EAimTY/tuic"

[dependencies]

lexopt = { version = "0.3", default-features = false }
socket2 = { version = "0.5", default-features = false }

uuid = { version = "1", default-features = false, features = ["serde", "std"] }

# QUIC
quinn = { branch = "main", git = "https://github.com/quinn-rs/quinn.git", default-features = false, features = ["runtime-tokio", "rustls", "platform-verifier", "log", "lock_tracking"] }

# TUIC
tuic = { path = "../tuic", default-features = false }
tuic-quinn = { path = "../tuic-quinn", default-features = false }
register-count = { version = "0.1.0", default-features = false, features = ["std"] }

# Tokio/Async
crossbeam-utils = { version = "0.8", default-features = false, features = ["std"] }
tokio = { version = "1", default-features = false, features = ["io-util", "macros", "net", "parking_lot", "rt-multi-thread", "time"] }
tokio-util = { version = "0.7", default-features = false, features = ["compat"] }

# TLS
rustls = { version = "0.23", default-features = false }
rustls-pemfile = { version = "2", default-features = false }

# Serde
bytes = { version = "1", default-features = false, features = ["std"] }
serde = { version = "1", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1", default-features = false, features = ["std"] }

# Logging
log = { version = "0.4", default-features = false, features = ["serde", "std"] }
env_logger = { version = "0.11", default-features = false, features = ["humantime"] }
humantime = { version = "2", default-features = false }

# Error handling
thiserror = { version = "1", default-features = false }
anyhow = "1"